### PR TITLE
clock created

### PR DESCRIPTION
**Pull request by manoj-kumar-vst-au4**

### CODE REVIEW

**Comment by ruhan-khandakar-au3** [comment]
Create an analog and digital clock, and create good UI

**Comment by ruhan-khandakar-au3** [comment]
so have you completed this ??

**Comment by manoj-kumar-vst-au4** [comment]
Not yet but did not get any other idea?

**Comment by manoj-kumar-vst-au4** [comment]
I think i am done with this project, I also have another project of a todo app, so approve this project so that I can send you another project.

**Comment by ruhan-khandakar-au3** [comment]
No please, give chance to other

and can you show me the demo ?

**Pull request merged**
